# Generated by Django 4.2.7 on 2023-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datachunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('chunk', models.TextField(max_length=1000)),
                ('url', models.TextField()),
            ],
        ),
    ]
