# Generated by Django 4.2.7 on 2023-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachunk',
            name='chunk',
            field=models.TextField(),
        ),
    ]
