# Generated by Django 4.2.7 on 2023-11-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_datachunk_chunk_remove_datachunk_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datachunk',
        ),
    ]
