# Generated by Django 4.2.7 on 2023-11-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_datachunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datachunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('vector_DB', models.BinaryField()),
            ],
        ),
    ]
