# Generated by Django 4.2.7 on 2024-01-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datachunk',
        ),
    ]
